server:
  listenAddress: ":80"
  exposedAddress: "http://nb-server:8080"
  metricsPort: 9090
  healthcheckAddress: ":9000"
  logLevel: "info"
  logFile: "console"

  authSecret: "test-relay-auth-secret-key-1234"
  dataDir: "/var/lib/netbird"

  auth:
    issuer: "http://nb-server:8080/oauth2"
    dashboardRedirectURIs:
      - "http://localhost/nb-auth"
    cliRedirectURIs:
      - "http://localhost:53000/"

  store:
    engine: "sqlite"
    encryptionKey: "QZLVr/XmD8zE0h9JHdWkdCX2GXPUma+9dLSq2w1eS8I="
